#version: '3'
services:
  icandid2_front:
    build: 
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - "4201:4201"
      - "4202:4202"
    environment:
      - APP_ENV=dev
  resilience_front:
    build: 
        context: .
        dockerfile: docker/Dockerfile_resilience
    ports:
      - "4201:4201"
      - "4202:4202"
