import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'
 
Vue.use(MLInstaller)
 
export default new MLCreate({
  initial: 'en',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('en').create({
        language:"Language",
        en:"English",
        nl:"Nederlands",
        thislanguage:"English",
        projecttitle: "ReIReSearch",
        search: 'Search',
        searchresult: 'Searchresult',
        advancedsearch: 'Advanced Search',
        clearsearch:'Clear Search',
        simplesearch: 'Simple Search',
        suredeleteitemfromset : 'Are you sure you wish to delete this record from the set ?',
        suredeletesearchfromsaved : 'Are you sure you wish to delete this search from the saved searches ?',
        suredeleteset: 'Are you sure you wish to delete this complete set ?',
        statistics:'Statistics',
        about:'About',
        aboutresilience:"About ReIReSearch",
        aboutdatasets:"About datasets",
        aboutcitations:"Cite ReIReSearch",
        howtocite:"How to cite ReIReSearch",
        help:'Help',
        profile:'Profile',
        logout:'Logout',
        login:'Login',
        savedsearches:'Saved Searches',
        savedrecords:'Saved Records',
        searchhistory:'Search History',
        allthewords:'All the words',
        oneofwords:'One of the words',
        exactsentence:'The exact sentence',
        yesterday:'Yesterday',
        lastweek:'Last week',
        lastmonth:'Last month',
        oneyear:'For one year',
        entirearchive:'Entire archive',
        all:'All',
        savequery:'Save query for later use',
        exportcsv:'Export the full result as CSV',
        exporttxt:'Export the full result as TXT',
        exportxlsx:'Export the full result as Excel',
        exportjson:'Export the full result as JSON-LD',
        exportsetcsv:'Export collection as CSV',
        exportsetxlsx:'Export collection as Excel',
        exportsettxt:'Export collection as TXT',
        exportsetjson:'Export collection as JSON-LD',
        platformby:'Platform by',
        type: 'Type',
        identifier: 'Identifier',
        publication:'Publisher',
        edition:"Edition",
        publicationdate: 'Publication date',
        dateline: 'Dateline',
        title: 'Title',
        title_warn: "Title is required",
        author: 'Author',
        description: 'Description',
        text: 'Text',
        keywords: 'Keywords',
        mentions: 'Mentions',
        duration: 'Duration',
        content: 'Content',
        link:'Link',
        permalink: 'Permalink',
        provider: 'Provider',
        provider_warn: "Provider is required",
        dataset:"Dataset",
        saveiteminset:'Save record(s) in \'Saved records\'',
        filters:'Filters',
        hits :'Hits',
        publisher:"Publisher",
        enternameofset:'Enter the name of the set you wish the item to be added to.',
        alternativeclick:'Alternatively double-click on the field below to get a list of the names of the sets you already have.',
        save:'Save',
        cancel:'Cancel',
        articlesperweek:'Articles per week',
        totalnumberofarticles:'Total number of items',
        numberofarticlespernewssource:'Number of articles per newssource',
        days:'days',
        articlespernewssourceperday : "Articles per newssource per day",
        numberofarticlespertype:'Number of items per type',
        numberofitemsperprovider:'Number of items per provider',
        last:'Last',
        accessdenied:'Access denied',
        youhavenoaccess:'You have no access',
        recordnotfound:'Record not found',
        sortby:'Sort by',
        relevance:'Relevance',
        noresultsfound:'No results found',
        notice:'Notice',
        info:'Info',
        confirm:'Confirm',
        personalprofile:"Personal Profile",
        name:'Given name',
        lastname:'Last Name',
        fullname:"Name",
        email:'Email',
        and:"and",
        or:"or",
        not:"not",
        containsthewords:"contains the words",
        containsexactphrase:"contains the exact phrase",
        startswith:"starts with",
        any:"Any",
        exportinprogress:"Your export is being prepared.<br><br>You will receive a message at <b>{email}</b> when it is ready for download.",
        searchsaved:"The search is saved.",
        yes:"Yes",
        no:"No",
        ok:"Ok",
        period:"Period",
        from:"From",
        toandincluding:"to and including",
        dbinfotooltip:"Link to the original record on the providers website",
        NERModelsinuse:"NER models in use",
        sender:"Sender",
        recipient:"Reply to",
        ner_label_GPE:"Geopolitical entity",
        ner_label_PERSON:"People",
        ner_label_ORG:"Organization",
        ner_label_NORP:"Nationalities or religious or political groups",
        ner_label_FAC:"Building",
        ner_label_WORK_OF_ART:"Work of art",
        ner_label_LOC:"Geographical locations",
        ner_label_EVENT:"Event",
        ner_label_DATE:"Date",
        ner_label_CARDINAL:"Cardinal number",
        ner_label_ORDINAL:"Ordinal number",
        ner_label_PRODUCT:"Object",
        ner_label_LANGUAGE:"Language",
        ner_label_TIME:"Time",
        ner_label_LAW:"Laws",
        ner_label_QUANTITY:"Quantity",
        ner_label_MONEY:"Monetary values",
        ner_label_PERCENT:"Percentage",
        retweeted_tweet:"Retweeded tweet",
        onlyretweet:"Only retweets",
        noretweet:"No retweets",
        retweet:"Retweets",
        retweets:"Retweets",
        replied_to_tweet:"Replied to tweet",
        quoted_tweet:"Quoted tweet",
        eula:"Terms of use",
        visualizations:"Visualizations",
        heatmap:"Word Heatmap",
        heatmap_info:"A heatmap is a visualization technique that represents the size of data using color. With this graph, you can visualize in how many records from your search results a word occurs over time and per publication. At the bottom, you can enter a search term and press 'enter'. Using color shades, you can see in how many records from your search results the term occurs. That frequency is calculated based on the number of records in which the term occurs. When a term occurs multiple times in the same record, it is counted as one occurrence.",
        treemap:'Publications Treemap',
        treemap_info:"A treemap is a method of visualizing data using figures. In this case, rectangles are used to visualize in which publications the search terms you entered appear most often. That frequency is calculated based on the number of records in which the term occurs. When a term occurs multiple times in the same record, it is counted as one occurrence.",
        bargraph:"Words Bargraph",
        bargraph_info:"The bargraph shows the frequency distribution of words in the records from your search results. With this graph, you can visualize in how many records from your search results a word occurs over time. That frequency is calculated based on the number of records in which the term is used. When a term occurs several times in the same record, this is counted as one occurrence.</p><p>For this you need to enter additional search terms in the appropriate field on the right. If you have 100 search results and enter the term \"face mask\", the bargraph shows in how many of the 100 records the word occurs from day to day. After entering a term, press 'enter' and you can enter more terms if desired.</p><p>If the bargraph is difficult to read due to the amount of search results, you can always search within a shorter period of time.", 
        bubblechart:"Authors Bubblechart",
        bubblechart_info:"The bubble chart is used to visualize the relative amount of contributions made by an author in your search results. The size of the figures clearly show which author contributed to the most records within your results. Depending on the amount of records in your search results, it is possible that not all authors are shown, but only the most frequently occuring ones",
        wordcloud:"Wordcloud",
        wordcloudner:"Wordcloud Named Entities",
        wordcloudner_info:"The Wordcloud shows the named entities that appear most often in your search results. The size of a named entity in the word cloud reflects the frequency of use. A named entity is a proper name that refers to a person, location, organization, product, etc. The named entities are retrieved from the records via automated named-entity recognition.",
        top10:"Top 10",
        top10_info:"Two things are shown in this visualization. On the left, the top ten news sources are listed in order of which ones your searched keywords appears most often. On the right, the top ten named entities that appear in your search results most often are listed. A named entity is a proper name that refers to a person, location, organization, product, etc. The named entities are retrieved from the records via automated named-entity recognition.",
        network:"Network",
        requestnewsletter:"Would you like to receive updates about new developments in ReIReSearch?",
        network_info:"This visualization only applies to search results from Twitter. It shows you the interactions between twitter profiles within the records resulting from your search. Retweets are shown in the visualization with the originally referenced profile in the center. The larger this central figure is compared to other figures, the more often it is referred to via retweet, relatively speaking.",
        home_title:"About ReIReSearch",
        home_intro:"ReIReSearch offers innovative and integrated access to metadata about various types of textual and audio-visual material from the main news databases in Flanders (GoPress Academic and ENA), as well as freely accessible online sources (e.g. Twitter data). ReIReSearch allows users to efficiently search for relevant text and fragments in large amounts of unstructured data. ReIReSearch includes export functionalities to ensure that researchers working with large datasets of socially significant data can analyze this data using existing analytical tools for quantitative and qualitative textual analysis as well as software tools for automated visual analysis.",
        home_limited:"ReIReSearch is currently only available to KU Leuven staff and students and access to the platform needs to be requested. To request access to ReIReSearch as a KU Leuven user in the context of your research, please contact <a href=\"mailto:ReIReSearch@kuleuven.be\">ReIReSearch@kuleuven.be</a>.",
        home_notloggedin:"If you have requested and obtained access, you can <a href=\"/login\">login here</a>",
        home_moreinfo:"More information about the ReIReSearch platform, the data that can be discovered and the terms of use can be found in the 'About' section.",
        onesearchterm:"Please enter at least 1 searchterm",
        selectall:"Select all results",
        requests:"Requests",
        dataset_on_demand:"Dataset-request",
        access:"Access-request",
        namefirstname:"Name and given name",
        namefirstname_warn:"Name and given name are mandatory",
        email_warn:"Email is invalid",
        institution:"Institution",
        kuleuven:"KU Leuven",
        other:"Other",
        institutionname:"Name of institution",
        institutionname_warn:"Name of institution is mandatory",
        functiontitle:"Position",
        researcher:"Researcher",
        student:"Student",
        functiontitle_warn:"Position is mandatory",
        promotor:"Promotor",
        promotor_warn:"Promotor is mandatory",
        faculty:"Faculty",
        faculty_warn:"Faculty is mandatory",
        researchgroup:"Research group",
        researchgroup_warn:"Researchgroup is mandatory",
        personel_student_no:"Personnel or studentnumber",
        personel_student_no_warn:"Personnel or studentnumber is mandatory",
        requestreason:"Motivation for the request",
        requestreason_warn:"Motivation for the request is mandatory",
        requestduration:"Duration",
        requestduration_warn:"Duration is mandatory",
        accessReIReSearchmedia1:"Access to ReIReSearch Media (Official pressmedia / social pressmedia)",
        accessReIReSearchmedia2:"Access to ReIReSearch Media (ENA / social pressmedia)",
        accesscollectionregister:"Access to ReIReSearch Collectionregister",
        datasets:"Datasets",
        chooseonedataset:"Choose at least one dataset",
        requestfunctionality:"Which functionalities do you wish to access?",
        chooseone:"Choose at least one",
        termsofuse:"I accept the <a href=\"/#/eula\" target=\"_blank\">terms of use</a>",
        requestanswerpos:": <p>Your request is being processed.<p> <br><p>ReIReSearch is run by a small team. Applications are usually processed within one month.<p><br><p>For additional questions, please contact <a href=\"mailto:ReIReSearch@kuleuven.be\">ReIReSearch@kuleuven.be</a> </p> ",
        requestanswerneg:"<p class=\"has-text-danger\">Something went wrong with your request.<p> <br><p>Please contact <a href=\"mailto:ReIReSearch@kuleuven.be\">ReIReSearch@kuleuven.be</a></p>",
        back:"Back",
        next:"Next",
        sendrequest:"Send request",
        refresh:"Refresh",
        searchterms: "Searchterms or searchquery",
        searchterms_warn: "Searchterms or searchquery is required",
        additionalinfo:"Additional information",
        edit:"Edit",
        apikey:"API-key",
        newapikey:"New API-key",
        delete:"Delete",
        eppn:"Loginname",
        newuser:"New user",
        newapikeyph:"API-key will be automatically generated when saving",
        users:"Users",
        newdataset:"New dataset",
        internalident:"Internal Identifier",
        talen:"Languages",
        labels:"Labels",
        label:"Label",        
        requestor:"Requestor/creator",
        requestoremail:"Email of requestor/creator",
        query:"Detailed description"  , 
        available:"Available",
        groups:"Groups",
        group:"Group",
        newgroup:"New group",
        newlabel:"New label",
        accessrights:"Accessrights",
        function:"Functionality",
        admin:"Admin",   
        media:"Online access",
        collections:"Collection Registry",
        notavailable:"Not available",
        showonlyavailablecollections:"Only show available collections",
        cleardates:"Clear dates",
        reallydeluser:"Are you sure you wish to delete this user ? This cannot be undone !",
        size:"Size",
        documents:"records",
        youalreadyhaveaccess:"You have access to this collection",
        requestdatasetaccess:"Request access",
        unavailable:"Unavailable",
        allusers:"All users",
        activeusers:"Active users",
        inactiveusers:"Inactive users",
        active:"Active",
        fieldrequired:"This field is required",
        validityperiod:"Validity period",
        message:"Message",
        lastcount:"last count on",
        license:"License",
        texts:"Texts",
        preview:"Preview",
        collections_:"Collections",
        functions:"Functions",
        selectevery:"select all",
        selectnone:"select none",
        hidden:"Hidden",
        sensitivecollection:"(for collections with sensitive content)",
        periodinfotooltip:"Use advanced search \"period\" to search on a specific date range",
        typeinfotooltip:"Use advanced search for Boolean operators",
        newsletter:"Newsletter",
        exportusers:"Export all users as Excel",
        pagination:"Pages",
        articlesection:"Section",
        location:"Location",
        sdDatePublished:"Stored in ReIReSearch on",
        updatetime:"Last modified in ReIReSearch on",
        twitter:"Twitter",
        apikeysecret:"API-key Secret",
        bearertoken:"Bearer Token",
        name_warn:"Name is mandatory",
        lastname_warn:"Lastname is mandatory",
        userexists:"A user with this loginname already exists",
        legislationPassedBy:"Petitioner",
        legislationType:"Documentype",
        legislationResponsible:"Responsible minister",
        volume:"Volume",
        issue:"Issue",
        showmore:"Show more",
        showless:"Show less",
        onlineonly:"Online access",
        infoonlineonly:"Toggle check to search for results for which a digital copy is available online",
        subject:"Subject",
        isbn:"ISBN",
        issn:"ISSN",
        locationcreated:"Publication place",
        subjects:"Subjects",
        contributor:"Contributor",
        online:"Online",
        metadatapublicationdate:"Metadata publication date",
        last2week:"Last 2 weeks",
        last3month:"Last 3 months",
        last6month:"Last 6 months",
        lastyear:"Last year",
        until:"Until",
        datePublishedAsc:"Date published - oldest first",
        datePublishedDesc:"Date published - newest first",
        honorificPrefix:"Honorific Prefix",
        honorificSuffix:"Honorific Suffix",
        familyName:"Family Name",
        additionalName:"Additional Name",
        gender:"Gender",
        nationality:"Nationality",
        birthDate:"Birth date",
        birthPlace:"Birth place",
        deathDate:"Death date",
        deathPlace:"Death place",
        alumniOf:"Alumni of",
        creator:"Creator",
        editor:"Editor",
        illustrator:"Illustrator",
        translator:"Translator",
        isPartOf:"Is part of",
        page:"Page",
        numberOfPages:"Number of pages",
        hasPart:"has part",
        dateCreated:"Creation date",
        locationCreated:"Publication place",
        sdPublisher:"Record publisher",
        includedInDataCatalog:"Included in Data Catalog",
        startDate:"Start date",
        endDate:"End date",
        additionalType:"Additional Type",
        type_additionalType:"Type, Additional Type",
        subjectOf:"Subject of",
        spatialCoverage:"Spatial Coverage",
        temporalCoverage:"Temporal Coverage",
        distribution:"Distribution",
        copyright:"Copyright",
        bookEdition:"Edition of book",
        material:"Made of",
        review:"Review",
        itemReviewed:"Item Reviewed",
        translationOfWork:"Translation of work",
        workTranslation:"Has translation",
        version:"Version",
        citation:"Citation",
        copylink:"Copy link to clipboard",
        linkcopied:"Link copied to clipboard",
        send:"Send",
        copytoclipboard:"Copy to clipboard",
        citationcopied:"Citation copied to clipboard",
        fullview:"Full view",
        emailissent:"Your message has been sent"
    }) ]
})