---
:queries:
- :query:
    :value: "(#migratie OR #migranten OR #vluchtelingen) lang:nl"
    :id: twitter_query_0000001
    :name: twitter_migratie
    :desc: Tweets about migratie with lang:nl. Starting from 21/03/2006
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2006-03-21T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2006-02-28'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-25T11:22:52Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(#klimaat OR #klimaatverandering) lang:nl"
    :id: twitter_query_0000002
    :name: twitter_klimaat
    :desc: Tweets about klimaat with lang:nl. Starting from 21/03/2006
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2006-03-21T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2006-02-28'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-25T11:22:52Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(Blankenberge OR Kust OR kuststad OR Rellen OR Mars OR Betoging OR Straffeloosheid
      OR Oostende OR Racisme) (from:tomvangrieken OR from:FDW_VB OR from:DVanLangenhove
      OR from:A_Tavernier OR from:Barbara_Pas OR from:SamvanRooy1 OR from:KarenLiesens
      OR from:Bart_DeWever OR from:FranckenTheo OR from:Zu_Demir OR from:A_Tavernier
      OR from:vlbelang OR from:vbjongeren OR from:VB_VlaParl OR from:VB_Kamer OR from:de_NVA
      OR from:Jongnva OR from:StefaanSintobin OR from:Anke_online OR from:Filip_Bru
      OR from:OrtwinDepo OR from:AnnickPonthier OR from:e_samyn OR from:TorbenGering
      OR from:karel_mortier OR from:lorinparys123)"
    :id: twitter_query_0000003
    :name: twitter_normalisering_extreemrechts
    :desc: Tweets from users about rellen, betoging, ... In dei periode 08/08/2020-30/09/2020
  :backlog:
    :start_date: '2020-08-08T00:00:00Z'
    :end_date: '2020-09-30T23:59:59Z'
    :current_process_date: '2020-07-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-19T18:42:40Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(#AllLivesMatter OR #BlackLivesMatter OR #BLMBelgium OR White privilege
      OR Racisme OR Racistisch OR Zwart OR Blank) lang:nl"
    :id: twitter_query_0000004
    :name: twitter_BLM_discussies_G_Floyd
    :desc: Tweets about \#BlackLivesMatter, rasisme, ... in het nederlands, In de
      periode 26/05/2020-04/06/2020
  :backlog:
    :start_date: '2020-05-26T00:00:00Z'
    :end_date: '2020-06-04T23:59:59Z'
    :current_process_date: '2020-04-30'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-19T19:37:19Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(Straffeloosheid OR Racisme) (from:tomvangrieken OR from:Bart_DeWever
      OR from:FranckenTheo OR from:Zu_Demir)"
    :id: twitter_query_0000005
    :name: twitter_dataset_extreemrechts  In de periode 08/08/2020-30/09/2020
    :desc: Tweets dataset Test
  :backlog:
    :start_date: '2020-08-08T00:00:00Z'
    :end_date: '2020-09-30T23:59:59Z'
    :current_process_date: '2020-07-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-19T18:42:40Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: from:vrtnws
    :id: twitter_query_0000006
    :name: twitter_nieuwsmedia_account
    :desc: All tweets from user vrtnws. Starting from 21/03/2006
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2006-03-21T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2006-02-28'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-25T11:22:52Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: from:VTMNIEUWS
    :id: twitter_query_0000007
    :name: twitter_nieuwsmedia_account
    :desc: All tweets from user VTMNIEUWS. Starting from 21/03/2006
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2006-03-21T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2006-02-28'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-25T11:22:52Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:demorgen OR from:destandaard OR from:tijd OR from:gva OR from:hbvl
      OR from:HLN_BE OR from:Nieuwsblad_be)"
    :id: twitter_query_0000008
    :name: twitter_nieuwsmedia_account
    :desc: All tweets from users demorgen destandaard tijd gva hbvl HLN_BE Nieuwsblad_be.
      Starting from 21/03/2006
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2006-03-21T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2006-02-28'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-25T11:22:52Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:spdde OR from:Die_Gruenen OR from:CDU OR from:CSU OR from:cducsubt
      OR from:AfD OR from:fdp OR from:dieLinke OR from:CDUMerkel OR from:ArminLaschet
      OR from:OlafScholz OR from:MartinSchulz OR from:ABaerbock OR from:GoeringEckardt
      OR from:cem_oezdemir OR from:SWagenknecht OR from:DietmarBartsch OR from:c_lindner
      OR from:Alice_Weidel OR from:AlexGauland OR from:Markus_Soeder OR from:Tino_Chrupalla
      OR from:JoanaCotar OR from:Janine_Wissler OR from:SusanneHennig OR from:Amira_M_Ali OR from:reinholdmdb)"
    :id: twitter_query_0000009
    :name: twitter_Duitse_politici_account
    :desc: Twitter accounts van Duitse Politici starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:rudi_anschober OR from:Haimbuchner OR from:matstrolz
      OR from:sebastiankurz OR from:rendiwagner OR from:norbertghofer OR from:BMeinl
      OR from:WKogler OR from:Peter_Pilz OR from:SPOE_at OR from:oevp OR from:FPOE_TV
      OR from:diegruenen OR from:neos_eu)"
    :id: twitter_query_0000010
    :name: twitter_Oostenrijkse_politici_account
    :desc: Twitter accounts van Oostenrijkse Politici starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:matteorenzi OR from:berlusconi OR from:luigidimaio OR from:PietroGrasso
      OR from:matteosalvinimi OR from:GiorgiaMeloni OR from:emmabonino OR from:nzingaretti
      OR from:pdnetwork OR from:forza_italia OR from:Mov5Stelle OR from:liberi_uguali
      OR from:LegaSalvini OR from:FratellidItalia OR from:Piu_Europa)"
    :id: twitter_query_0000011
    :name: twitter_Italiaanse_politici_account
    :desc: Twitter accounts van Italiaanse Politici starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:_miniszterelnok OR from:Viktor_Orban OR from:FideszEP OR from:JobbikMM
      OR from:Jobbik OR from:JobbikPP OR from:PeterJakab1 OR from:MZSP OR from:Bajnai_Gordon
      OR from:mszptweet OR from:Kisgazdapart OR from:lehet_mas)"
    :id: twitter_query_0000012
    :name: twitter_Hongaarse_politici_account
    :desc: Twitter accounts van Hongaarse Politici starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:tomvangrieken OR from:Barbara_Pas OR from:Zu_Demir OR from:FranckenTheo
      OR from:Maggie_DeBlock OR from:VincentVQ OR from:AnneliesVl OR from:SammyMahdi
      OR from:pdsutter OR from:kristofcalvo OR from:HanneloreGoeman OR from:HannesAnaf
      OR from:LiseVDC OR from:RaoulHedebouw OR from:alexanderdecroo)"
    :id: twitter_query_0000013
    :name: twitter_Vlaamse_politici_account
    :desc: Twitter accounts van Vlaamse Politici starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:DVanLangenhove OR from:KatleenBury OR from:StevenCreyelman OR from:spiegeleer13
      OR from:OrtwinDepo OR from:DewulfNathalie OR from:DillenMarijke OR from:ErikGilissen
      OR from:Barbara_Pas OR from:AnnickPonthier OR from:KurtRavyts OR from:e_samyn
      OR from:DominiekSneppe OR from:FrankTroosters OR from:tomvangrieken OR from:reccino
      OR from:WouterVermeersc OR from:HansVerreyt)"
    :id: twitter_query_0000014
    :name: twitter_Vlaams_Belang_account_masterproef_M_Depraetere
    :desc: Twitter accounts van Vlaams Belang starting from 01/01/2015
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2015-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2014-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: "(from:swedense OR from:belgiumbe)"
    :id: twitter_query_0000015
    :name: twitter_offical_country_account
    :desc: Official Twitter accounts from European countries starting from 01/01/2014
  :recent_records:
    :newest_id: 
    :last_run_update: '2022-06-16T02:30:06Z'
    :next_token: ''
    :url: 
  :backlog:
    :start_date: '2014-01-01T00:00:00Z'
    :end_date: '2022-05-18T00:00:00Z'
    :current_process_date: '2013-12-31'
    :next_token: ''
    :url: 
    :completed: true
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-06-16T08:00:04Z'
- :query:
    :value: (NFT OR NFTs OR "non-fungible token" OR "non-fungible tokens" OR "non fungible token" OR "non fungible tokens") lang:en
    :id: twitter_query_0000016
    :name: twitter_NFT
    :desc: Tweets containing NFT OR non-fungible token between 2020-12-15 and 2021-03-31
  :backlog:
    :start_date: '2020-12-15T00:00:00Z'
    :end_date: '2021-03-31T23:59:59Z'
    :current_process_date:
    :next_token: ''
    :url:
    :completed: false
    :last_run_update: '2022-05-20T22:44:58Z'
  :last_parsing_datetime: '2022-07-20T12:18:30Z'