---
:base_url: https://ws.vlpar.be
:opendata_url: https://ws.vlpar.be/e/opendata
:testing: true
:save_raw_data: true
:source_records_base_dir: "/source_records/VlaamsParlement"
:source_records_dir: "/source_records/VlaamsParlement/{{query_id}}/{{date}}/"
:records_dir: "/records/VlaamsParlement/{{query_id}}/new/{{date}}/"
:source_file_name_pattern: "*.json"
:dir_based_on_datePublished: false
:override_parsed_records: true
:rule_set: RULE_SET_v1_1
:recent_url: "{{base_url}}/api/search/query/{{query}}+inmeta:publicatiedatum:daterange:{{start_date}}..&requiredfields=paginatype:Parlementair%20document{{aggregation}}?collection=vp_collection&sort=date&max={{max_results}}&page={{page}}"
:backlog_url: "{{base_url}}/api/search/query/{{query}}+inmeta:publicatiedatum:daterange:{{start_date}}..{{end_date}}&requiredfields=paginatype:Parlementair%20document{{aggregation}}?collection=vp_collection&sort=date&max={{max_results}}&page={{page}}"
:meeting_url: "{{opendata_url}}/verg/{{uuid}}"
:legislatures_url: "{{opendata_url}}/leg/alle"
:committees_legislature_url: "{{opendata_url}}/comm/legislatuur?legislatuur={{legislatuur_uuid}}"
:committee_url: "{{opendata_url}}/comm/{{uuid}}/alle-stvz"
:pi_url: "{{opendata_url}}/pi/{{uuid}}"
:encode_query_value: false
:tika_server: services3.libis.be
:status: downloading
