---
:queries:
- :query:
    :value: ''
    :aggregation: ".aggregaat:Voorstel%20of%20ontwerp%20van%20decreet%7Caggregaat:Begrotingsontwerp%20en%20-documenten%7Caggregaat:Beleidsdocument%20van%20de%20Vlaamse%20Regering%7Caggregaat:Conceptnota%20voor%20nieuwe%20regelgeving%7Caggregaat:Voorstel%20van%20resolutie%7Caggregaat:Motie%7Caggregaat:Actualiteitsdebat%7Caggregaat:Verslag%20van%20commissie%20of%20plenaire%20vergadering%7Caggregaat:Amendement%7Caggregaat:Advies%20of%20verslag%20van%20Rekenhof,%20Raad%20van%20State%20en%20andere%7Caggregaat:Interne%20werking%20Vlaams%20Parlement"
    :id: vlpar_opendata_query_0000001
    :name: documenten_vlaams_parlement
    :desc: Documents from Flemish Parliament (http://ws.vlpar.be/)
  :recent_records:
    :start_date: 2023-01-01
    :last_run_update: '2023-01-09T14:50:18Z'
  :backlog:
    :start_date: '2000-01-01T00:00:00Z'
    :end_date: '2022-12-31T00:00:00Z'
    :current_process_date: '2004-01-31'
    :completed: 
    :last_run_update: '2023-01-06T16:42:12Z'
  :last_parsing_datetime: 
