---
:queries:
- :query:
    :value: genres=sci_fi&count=250&sort=release_date,asc
    :id: imdb-api_query_00001
    :name: SciFi IMDB
    :desc: SciFi movies in IMDB
  :recent_records:
    :start_date: ''
    :last_run_update: '2023-11-23T15:17:45Z'
    :url:
  :last_parsing_datetime: '2023-10-03T05:05:03Z'
