FROM ruby:2.7.1

# Install gems
ENV APP_HOME /app
ENV HOME /root

RUN cp /usr/share/zoneinfo/CET /etc/localtime 

RUN apt-get update
RUN apt-get install sgrep

RUN mkdir $APP_HOME

ADD gems/data_collector_gem $APP_HOME/data_collector
WORKDIR $APP_HOME/data_collector
RUN gem build data_collector.gemspec
RUN gem install data_collector-0.0.1.gem

WORKDIR $APP_HOME
COPY Gemfile ./
RUN gem install bundler
RUN bundle install

COPY src /app/src
