source "https://rubygems.org"

gem 'http'
gem 'mime-types'
gem 'nokogiri'
gem 'nori'
gem 'json'
gem 'jsonpath', ' 1.0.4'
gem 'activesupport'
gem 'minitar'
gem 'minitar-cli'
gem 'oai'
gem 'iso639'
gem "iso8601"
gem 'unicode'
gem "unicode-scripts"
gem "net-ftp-list"
gem "zip"
gem "get_process_mem"
gem "xml_split"


